#!/bin/bash

# Start the database
docker compose up -d postgres

# Wait until Postgres is ready.
docker compose run phoenix bash -c '\
  while ! pg_isready -h postgres -p $PGPORT -U $PGUSER; do \
    echo "$(date) - Waiting for postgres to start..."; \
    sleep 1; \
  done'

# Apply database migrations and start the server with Iex
exec docker compose run --service-ports phoenix bash -c "mix ecto.create && mix ecto.migrate && iex -S mix phx.server"
