#!/bin/bash

# Start the database
docker compose up -d postgres

# Apply database migrations and start the server with Iex
exec docker compose run --service-ports phoenix bash -c "mix ecto.create && mix ecto.migrate && iex -S mix phx.server"
